// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_eLyPqEooWt90n4nms8Cy009MNnpQYw',
    appId: '1:1012323754832:web:0456fa1f8cd7133a43c255',
    messagingSenderId: '1012323754832',
    projectId: 'lombardspb-a2919',
    authDomain: 'lombardspb-a2919.firebaseapp.com',
    storageBucket: 'lombardspb-a2919.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5C682_gRPMjqNzr-N_BUvki1BJ6LSp94',
    appId: '1:1012323754832:android:8226d32298dbef9543c255',
    messagingSenderId: '1012323754832',
    projectId: 'lombardspb-a2919',
    storageBucket: 'lombardspb-a2919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAek4hXQY9YuKJqBCJUDdUeDnE-1aMYI14',
    appId: '1:1012323754832:ios:c70370cb5db2ff0343c255',
    messagingSenderId: '1012323754832',
    projectId: 'lombardspb-a2919',
    storageBucket: 'lombardspb-a2919.firebasestorage.app',
    iosBundleId: 'best.app.lombardspb',
  );
}
